"""New users model

Revision ID: a40853086b4f
Revises: 4221cdf451ce
Create Date: 2026-01-26 15:03:35.101910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a40853086b4f"
down_revision: Union[str, None] = "4221cdf451ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_column("users", "role")
    op.drop_column("users", "balance")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users", sa.Column("balance", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("role", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users", sa.Column("created_at", sa.DATE(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
