"""New payments model

Revision ID: 53b981005245
Revises: 3ec53bbfb6fc
Create Date: 2026-01-26 14:18:15.162955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "53b981005245"
down_revision: Union[str, None] = "3ec53bbfb6fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("case_id", sa.Integer(), nullable=False))
    op.add_column("payments", sa.Column("amount", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "payments", "users", ["case_id"], ["id"])
    op.drop_column("payments", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("status", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_column("payments", "amount")
    op.drop_column("payments", "case_id")
    # ### end Alembic commands ###
