"""New model for items

Revision ID: 4582be9219d8
Revises: 8d9cb2a67e4d
Create Date: 2026-01-25 22:02:17.639468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4582be9219d8"
down_revision: Union[str, None] = "8d9cb2a67e4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("case_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "items", "cases", ["case_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "items", type_="foreignkey")
    op.drop_column("items", "case_id")
    # ### end Alembic commands ###
