"""New payments model

Revision ID: 3ec53bbfb6fc
Revises: 4582be9219d8
Create Date: 2026-01-26 13:29:11.641144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3ec53bbfb6fc"
down_revision: Union[str, None] = "4582be9219d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("price", sa.Integer(), nullable=False))
    op.add_column("payments", sa.Column("date", sa.Date(), nullable=False))
    op.drop_column("payments", "amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("payments", "date")
    op.drop_column("payments", "price")
    # ### end Alembic commands ###
