"""My migration

Revision ID: 8d9cb2a67e4d
Revises: adbfb6caf2a4
Create Date: 2026-01-25 15:46:37.196682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8d9cb2a67e4d"
down_revision: Union[str, None] = "adbfb6caf2a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
